[package]
name = "sftp-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
chrono = "0.4.42"
config = "0.15.18"
tracing-subscriber = "0.3.20"
